let vokabulary = JSON.parse(localStorage.getItem('vokabulary')) || 
 {
    "berg": "mountain",
    "die, diese": "these",
    "geben": "give",
    "grillfest": "barbecue",
    "heiß": "hot",
    "herumlaufen": "walk around",
    "kalt": "cold",
    "kurz": "short",
    "morgen": "tomorrow",
    "regen": "rain",
    "regnerisch": "rainy",
    "schön": "beautiful",   
    "see": "lake",
    "sie waren nicht": "they weren't",
    "sonne": "sun",
    "sonnig": "sunny",
    "test": "test",
    "warm": "warm",
    "wetter": "weather",
    "ziehen": "pull",
    "chain": "kette",
    "wir hatten kein": "we didn't have",
    "ich bekam": "i got",
    "sein name": "its name",
    "ziemlich": "quite",
    "in der pause": "at break",
    "alleine": "alone",
    "lang": "long",
    "kurz": "short",
    "mitteilungsblatt": "newspaper",
    "mittagszeit": "lunchtime",
    "nicht fit": "unfit",
    "fit werden": "get fit",
    "experiment": "experiment",
    "theater spielen": "act",
    "ich machte": "i did",
    "weihnachten": "christmas",
    "gesund": "healthy",
    "lecker": "yummy",
    "auslflug": "trip",
    "welcher klub": "wich club",
    "projekt": "project",
    "besser": "better",
    "mehr ideen": "more ideas",
    "etwas heraus finden": "find something out",
    "etwas einsetzten": "put something in",
    "kreis": "circle",
    "also": "so",
    "kanal": "channel",
    "fahren": "drive",
    "freunde finden": "make firends",
    "heimweh haben": "feel homesick",
    "gegenwart": "present",
    "vergangenheit": "past",
    "regel": "rule",
    "satz": "sentence",
    "suchen": "look for",
    "jemanden fragen": "ask somebody",
    "zum schluss": "in the end",
    "gewinner": "winner",
    "jeder": "each",
    "beenden": "finish",
    "vergessen": "forget",
    "vergaß": "forgot",
    "ein paar": "a few",
    "minute": "minute",
    "ein paar minuten": "for a few minutes",
    "als nächstes": "next",
    "ein anderer": "another",
    "ohne": "without",
    "antwort": "answer",
    "als": "when",
    "zuerst": "at first",
    "etwas holen": "get something",
    "schulhof": "school yard",
    "warten auf": "wait for",
    "überrascht": "surprised",
}